destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    false
markdown:    rdiscount
textile:     redcloth
permalink:   /:year/:month/:day/:title

# Site-wide constants
prototype:
  latest_stable_version: "1.7.1"
  latest_stable_release_date: "June 5, 2012"
  latest_stable_url: "https://ajax.googleapis.com/ajax/libs/prototype/1.7.1.0/prototype.js"
  latest_edge_version: false
  latest_edge_url: ""